#!/usr/bin/env bash

# DTM Migrations - create-opposites command
# Create Opposite References for DTM Assets

# import shared functions

# shellcheck source=/dev/null
source "$(dirname "$0")/../_shared/helper"
source "$(dirname "$0")/../_shared/constants"

# Stop on unexpected errors
set -e


# Help text
help() {
    cat <<EOF
Create Opposite references for DTM Assets with c8y_LinkedSeries fragment.

Usage:
    c8y dtm migration create-opposites [args...]

Description:
    Creates opposite references for all Assets that have the c8y_LinkedSeries fragment. 
    For each linked series, an opposite reference will be created as ChildAddition of the linked device using the 
    /assets/{id}/linkedSeries/{fragment}/{series}/opposite endpoint.


Flags:
    -h, --help                 Show this help message
    --dryRun                   Show what would be done, without making any changes.

Examples:
    c8y dtm migration create-opposites --removeMissingSourceId

Requirements:
    - go-c8y-cli authenticated session
    - jq for JSON processing
EOF
exit 0
}

# Default values
POSITIONAL_ARGS=()

# Parse arguments
while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)
            help
            ;;
        *)
            POSITIONAL_ARGS+=("$1")
            ;;
    esac
    shift
done

export ALLOWED_FLAGS=(
  --cache --cacheBodyPaths --cacheTTL --debug --delay --delayBefore --dry --header -k --insecure -l --logMessage --maxJobs --noAccept -M --noColor --noCache --progress --timeout --totalErrors --workers --verbose
)

# Restore additional arguments
set -- "${POSITIONAL_ARGS[@]}"

validate_positional_args "$@"

check_prerequisites

export FILTER_QUERY="has(${LINKED_SERIES_FRAGMENT})"
export EXTRA_SELECT_FIELDS="${LINKED_SERIES_FRAGMENT}"
assets_with_linked_series=$(load_all_assets)

if is_empty_result_set "$assets_with_linked_series" ; then
    info "No assets to handle. Exiting."
    exit 0
fi

total_collected=$(count_lines "$assets_with_linked_series")
info "Server returned $total_collected assets with linked series..."

# If we don't have any assets with linked series to handle, we can exit early.
if [ "$total_collected" -eq 0 ]; then
    info "No assets with linked series to process. Exiting."
    exit 0
fi

# Get only the data we need for the next steps, and simplify the structure for easier processing
explodedSeries=$(echo "$assets_with_linked_series" | jq -c '. as $parent | .c8y_LinkedSeries[] as $item | select($item.source.id != null) | $parent | .c8y_LinkedSeries = $item')
# echo "$explodedSeries" | jq

total_collected=$(count_lines "$explodedSeries")
info "...of which $total_collected have linked series with source.id that can be processed."

#If we don't have any assets with linked series to handle, we can exit early.
if [ "$total_collected" -eq 0 ]; then
    info "No assets with linked series and source.id to process. Exiting."
    exit 0
fi

childAddtions=$(printf '%s' "$explodedSeries" | jq -c -s 'map({
        source_id: .c8y_LinkedSeries.source.id,
        linked_asset: (
            . as $parent |
            {
                asset: ($parent.c8y_LinkedSeries | del(.source) + {id: $parent.id})
            } + ($parent.c8y_LinkedSeries.source | del(.id))
        )
    })
    | group_by(.source_id)
    | map({
        id: .[0].source_id,
        c8y_LinkedAssets: map(.linked_asset)
    })
    | .[]')

# echo "$childAddtions" | jq 

echo "$childAddtions" | c8y devices children create \
        --childType "addition" \
        --template '{ c8y_LinkedAssets: input.value.c8y_LinkedAssets }' \
        "${C8Y_FLAGS[@]}"

# to use the opposite endpoint, 
# echo "$explodedSeries" | jq -r '"/assets/" + .id + "/linkedSeries/" + .c8y_LinkedSeries.fragment + "/" + .c8y_LinkedSeries.series + "/opposite"' | c8y api --method PUT --url "%s${missingSourceOption}" "${C8Y_FLAGS[@]}"

return_code=$?
if [ $return_code -ne 0 ]; then
    error "Error during processing." "Failed to create at least one opposite reference. API call returned with code $return_code."
    exit $return_code
fi

success "Completed."
exit 0
