#!/usr/bin/env bash

# DTM Migrations - create-opposites command
# Create Opposite References for DTM Assets

# import shared functions

# shellcheck source=/dev/null
source "$(dirname "$0")/../_shared/helper"
source "$(dirname "$0")/../_shared/constants"

# Stop on unexpected errors. Ensure that pipelines return the correct exit code.
set -eo pipefail

# Help text
help() {
    cat <<EOF
Create Opposite references for DTM Assets with c8y_LinkedSeries fragment.

Usage:
    c8y dtm migration opposites [create|clear] [args...]

Description:
    Creates or removes opposite references for all Assets that have the c8y_LinkedSeries fragment. 
    In create mode, for each linked series an opposite reference will be created as ChildAddition of the linked device.
    In clear mode, all opposite references will be removed.

Flags:
    -h, --help                 Show this help message

Examples:
    c8y dtm migration opposites create
    c8y dtm migration opposites clear

Requirements:
    - go-c8y-cli authenticated session
    - jq for JSON processing
EOF
exit 0
}

# Default values
POSITIONAL_ARGS=()
MODE=""

checkDefiningModeTwice() {
    if [ -n "$MODE" ]; then
        error "Bad args:" "Cannot specify more than one mode. Already set to '$MODE'."
        exit 1
    fi
}

checkModeIsSet() {
    if [ -z "$MODE" ]; then
        error "Bad args:" "No mode specified. Please specify either 'create' or 'clear'."
        exit 1
    fi
}

# Parse arguments
while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)
            help
            ;;
        create)
            checkDefiningModeTwice
            MODE="create"
            ;;
        clear)
            checkDefiningModeTwice
            MODE="clear"
            ;;
        *)
            POSITIONAL_ARGS+=("$1")
            ;;
    esac
    shift
done

ALLOWED_FLAGS=(
  --force -f --cache --cacheBodyPaths --cacheTTL --debug --delay --delayBefore --dry --header -k --insecure -l --logMessage --maxJobs --noAccept -M --noColor --noCache --progress --timeout --totalErrors --workers --verbose
)

checkModeIsSet

# Restore additional arguments
set -- "${POSITIONAL_ARGS[@]}"

validate_positional_args "$@"

check_prerequisites

export FILTER_QUERY="has(${LINKED_SERIES_FRAGMENT})"
export EXTRA_SELECT_FIELDS="${LINKED_SERIES_FRAGMENT}"

if [ "$MODE" = "create" ]; then
    info "Running in CREATE mode."

    existing_reverses=$(c8y inventory find --pageSize 1 --type "c8y_LinkedSeriesReverseIndex")
    if ! is_empty_result_set "$existing_reverses"; then
        error "Existing references detected." "There are already opposite references in the tenant. Stopping."
        exit 1
    fi

    assets_with_linked_series=$(load_all_assets)

    if is_empty_result_set "$assets_with_linked_series" ; then
        info "No assets to handle. Exiting."
        exit 0
    fi

    total_collected=$(count_lines "$assets_with_linked_series")
    
    # If we don't have any assets with linked series to handle, we can exit early.
    if [ "$total_collected" -eq 0 ]; then
        info "No assets with linked series to process. Exiting."
        exit 0
    else
        info "Server returned $total_collected assets with linked series."
    fi

    # Get only the data we need for the next steps, and simplify the structure for easier processing
    explodedSeries=$(echo "$assets_with_linked_series" | jq -c '. as $parent | .c8y_LinkedSeries[] as $item | select($item.source.id != null) | $parent | .c8y_LinkedSeries = $item')

    total_collected=$(count_lines "$explodedSeries")

    #If we don't have any assets with linked series to handle, we can exit early.
    if [ "$total_collected" -eq 0 ]; then
        info "No assets with linked series and source.id to process. Exiting."
        exit 0
    else
        info "There are $total_collected assets that have linked series with source.id that can be processed."
    fi

    childAdditions=$(printf '%s' "$explodedSeries" | jq -c -s 'map({
            source_id: .c8y_LinkedSeries.source.id,
            linked_asset: (
                . as $parent |
                {
                    asset: ($parent.c8y_LinkedSeries | del(.source) + {id: $parent.id})
                } + ($parent.c8y_LinkedSeries.source | del(.id))
            )
        })
        | group_by(.source_id)
        | map({
            id: .[0].source_id,
            c8y_LinkedAssets: map(.linked_asset)
        })
        | .[]')

    echo "$childAdditions" | c8y devices children create \
            --childType "addition" \
            --template '{ c8y_LinkedAssets: input.value.c8y_LinkedAssets, type: "c8y_LinkedSeriesReverseIndex" }' \
            "${C8Y_FLAGS[@]}"

    # to use the opposite endpoint, 
    # echo "$explodedSeries" | jq -r '"/assets/" + .id + "/linkedSeries/" + .c8y_LinkedSeries.fragment + "/" + .c8y_LinkedSeries.series + "/opposite"' | c8y api --method PUT --url "%s${missingSourceOption}" "${C8Y_FLAGS[@]}"
elif [ "$MODE" = "clear" ]; then
    info "Running in CLEAR mode."
    
    c8y inventory find --includeAll --type "c8y_LinkedSeriesReverseIndex" | c8y inventory delete "${C8Y_FLAGS[@]}"
fi

success "Successfully handled all opposite references."
