#!/usr/bin/env bash

# Shared constants for DTM script commands

EXTERNAL_ID_FRAGMENT="c8y_ExternalId"
EXTERNAL_ASSET_FRAGMENT="c8y_ExternalAsset"
LINKED_SERIES_FRAGMENT="c8y_LinkedSeries"

export EXTERNAL_ID_FRAGMENT
export EXTERNAL_ASSET_FRAGMENT
export LINKED_SERIES_FRAGMENT